### ISSUE TITLE
How could we enable translucency?

### ISSUE THREAD

**Issue by joeharby** [oseparovic/MessageComposerView#11]
Is there an easy was to add translucency on the comments bar?

**Comment by oseparovic** [comment]
Currently the background color of the composer is set in the `setup` function via:
```
self.backgroundColor = [UIColor lightGrayColor];
```

If you want to override this you should be able to set the background to a `UIColor` with alpha < 1 at some point after you alloc and init to make it translucent E.g.
```
self.messageComposerView = [[MessageComposerView alloc] init];
self.messageComposerView.delegate = self;
self.messageComposerView.backgroundColor = [UIColor colorWithWhite:1.0 alpha:0.5];
```

**Comment by joeharby** [comment]
Thanks!
