### ISSUE TITLE
UITabbarController containing UINavigationBarControllers

### ISSUE THREAD

**Issue by Jenin** [oseparovic/MessageComposerView#12]
I have an app that has a UITabbarController, and for the first tab I have a uinavigationController.

If I present modally a viewController that uses MessageComposerView  it is working fine.

But the problem is If I push the view controller into the navigation controller! the accessoryView of MessageComposerView  will remain under the tabbar (invisible).

**Comment by oseparovic** [comment]
I haven't found a more elegant solution to this (if one exists) but a simple workaround would be to use:
```
// init with provided frame and offset between composer and keyboard/bottom of screen
- (id)initWithFrame:(CGRect)frame andKeyboardOffset:(NSInteger)offset;
```
And specify the height of your Tabbar as your keyboard offset.
