### ISSUE TITLE
Space between keyboard and textview

### ISSUE THREAD

**Issue by mbLc** [oseparovic/MessageComposerView#15]
Hi,

I just downloaded your lib and I have a space on iOS 9.2 between the keyboard and the textview with the send button. Works fine in landscape but not in portrait.
Did I miss something? I'm using the example in the readme:

> 
>     self.messageComposerView = [[MessageComposerView alloc] init];
>     self.messageComposerView.delegate = self;
>     [self.view addSubview:self.messageComposerView];

Thanks for your help

**Comment by oseparovic** [comment]
Hi I haven't had time to support the lib lately so it's likely a bug or an
incompatibility with a new device/os. What phone/version are you running it
on and what view are you adding it to?

**Comment by mbLc** [comment]
Thanks for the fast reply.

I tried on a fresh new UIViewController (single view), I just added the line you provided. I tried on a real iPhone 6S device and on an iPhone 5S with the simulator. Same result.
My project is set on iOS 8.0 and my phone got iOS 9.2.1

**Comment by oseparovic** [comment]
I had some unpushed commits from last time I was working on this. Can you
please do a pull and try again?

**Comment by mbLc** [comment]
Still not working.

> Using MessageComposerView (1.3.3)

**Comment by oseparovic** [comment]
It's not an official new version. 1.3.3 is still the old release from last
october you were using before.

**Comment by mbLc** [comment]
Sorry I didn't know. Anyway, everything is working fine now.

Thank you for your help!

**Comment by oseparovic** [comment]
Awesome. I'll update the pod version. Please let me know if there are any
other issues
